name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
  TF_VAR_region: ${{ secrets.REGION }}
  TF_VAR_zone: ${{ secrets.ZONE }}
  TF_VAR_budget_amount: ${{ secrets.BUDGET_AMOUNT }}
  TF_VAR_notification_email: ${{ secrets.NOTIFICATION_EMAIL }}
jobs:
  deploy:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: "actions/checkout@v4"
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: Authenticate with Google Cloud
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
      - name: format
        working-directory: ./gcp
        run: terraform fmt -check
      - name: init
        id: init
        working-directory: ./gcp
        run: terraform init
      - name: plan
        id: plan
        timeout-minutes: 3
        working-directory: ./gcp
        run: terraform plan
      - name: apply
        id: apply
        timeout-minutes: 3
        working-directory: ./gcp
        run: terraform apply -auto-approve
