name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_VAR_heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
jobs:
  deploy:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: "actions/checkout@v4"
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: format
        working-directory: ./heroku
        run: terraform fmt -check
      - name: init
        id: init
        working-directory: ./heroku
        run: terraform init
      - name: plan
        id: plan
        timeout-minutes: 3
        working-directory: ./heroku
        run: terraform plan
      - name: apply
        id: apply
        timeout-minutes: 3
        working-directory: ./heroku
        run: terraform apply -auto-approve
